sources_c_accel.o : \
	sources_pointmass.o

sources_cooling.o : \
	sources_pointmass.o

sources_diskthomson.o : \
	sources_pointmass.o

sources_generic.o : \
	sources_pointmass.o \
	sources_diskthomson.o \
	sources_viscosity.o \
	sources_c_accel.o \
	sources_selfgravitation.o \
	sources_boundary.o \
	sources_cooling.o

sources_selfgravitation.o : \
	sources_pointmass.o \
	sources_boundary.o

sources_viscosity.o : \
	sources_pointmass.o

