fluxes_trapezoidal.o : \
	fluxes_midpoint.o \
	reconstruction_generic.o

reconstruction_linear.o : \
	reconstruction_constant.o

fluxes_midpoint.o : \
	reconstruction_generic.o

reconstruction_generic.o : \
	reconstruction_constant.o \
	reconstruction_linear.o

fluxes_generic.o : \
	fluxes_midpoint.o \
	fluxes_trapezoidal.o \
	reconstruction_generic.o

