fluxes_common.o : \
	common_types.o \
	reconstruction_common.o

boundary_common.o : \
	common_types.o

constants_common.o : \
	common_types.o

fileio_common.o : \
	common_types.o \
	mesh_common.o \
	physics_common.o

reconstruction_common.o : \
	common_types.o

fosite_common.o : \
	common_types.o \
	mesh_common.o \
	fluxes_common.o \
	physics_common.o \
	fileio_common.o \
	timedisc_common.o

poisson_common.o : \
	common_types.o \
	multipole_common.o

timedisc_common.o : \
	common_types.o \
	boundary_common.o

sources_common.o : \
	common_types.o \
	mesh_common.o \
	poisson_common.o

multipole_common.o : \
	common_types.o \
	mesh_common.o

mesh_common.o : \
	common_types.o \
	geometry_common.o

physics_common.o : \
	common_types.o \
	sources_common.o \
	constants_common.o

geometry_common.o : \
	common_types.o

