boundary_axis.o : \
	boundary_reflecting.o

boundary_custom.o : \
	boundary_nogradients.o \
	boundary_fixed.o

boundary_extrapolation.o : \
	boundary_nogradients.o

boundary_farfield.o : \
	boundary_nogradients.o \
	boundary_fixed.o

boundary_fixed.o : \
	boundary_nogradients.o

boundary_folded.o : \
	boundary_reflecting.o

boundary_generic.o : \
	boundary_nogradients.o \
	boundary_periodic.o \
	boundary_reflecting.o \
	boundary_axis.o \
	boundary_folded.o \
	boundary_fixed.o \
	boundary_extrapolation.o \
	boundary_noh.o \
	boundary_noslip.o \
	boundary_custom.o \
	boundary_farfield.o

boundary_noh.o : \
	boundary_nogradients.o \
	boundary_fixed.o

boundary_noslip.o : \
	boundary_nogradients.o

boundary_periodic.o : \
	boundary_nogradients.o

boundary_reflecting.o : \
	boundary_nogradients.o

