geometry_cylindrical.o : \
	geometry_cartesian.o

geometry_sinhspherical.o : \
	geometry_cartesian.o \
	geometry_spherical.o

geometry_tancylindrical.o : \
	geometry_cartesian.o

geometry_logpolar.o : \
	geometry_cartesian.o

geometry_sinhpolar.o : \
	geometry_cartesian.o

geometry_polar.o : \
	geometry_cartesian.o

geometry_oblatespheroidal.o : \
	geometry_cartesian.o

mesh_generic.o : \
	mesh_midpoint.o \
	mesh_trapezoidal.o \
	geometry_generic.o

geometry_tanpolar.o : \
	geometry_cartesian.o

mesh_midpoint.o : \
	geometry_generic.o

geometry_spherical.o : \
	geometry_cartesian.o

mesh_trapezoidal.o : \
	mesh_midpoint.o \
	geometry_generic.o

geometry_generic.o : \
	geometry_cartesian.o \
	geometry_polar.o \
	geometry_logpolar.o \
	geometry_cylindrical.o \
	geometry_spherical.o \
	geometry_oblatespheroidal.o \
	geometry_tancylindrical.o \
	geometry_tanpolar.o \
	geometry_sinhpolar.o \
	geometry_sinhspherical.o

